targets = [ "//:ublas" ]

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
version = "1.65.1"

[[dependency]]
package = "github.com/buckaroo-pm/boost-core"
version = "1.65.1"

[[dependency]]
package = "github.com/buckaroo-pm/boost-mpl"
version = "1.65.1"

[[dependency]]
package = "github.com/buckaroo-pm/boost-serialization"
version = "1.65.1"

[[dependency]]
package = "github.com/buckaroo-pm/boost-static_assert"
version = "1.65.1"

[[dependency]]
package = "github.com/buckaroo-pm/boost-type_traits"
version = "1.65.1"

[[dependency]]
package = "github.com/buckaroo-pm/boost-typeof"
version = "1.65.1"
