manifest = "95cc650119be5b375111fe0c3d5920d82d29d629e5939c5fa4eeb6b12f1a75cf"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-core"
target = "//:core"

[[dependency]]
package = "github.com/buckaroo-pm/boost-mpl"
target = "//:mpl"

[[dependency]]
package = "github.com/buckaroo-pm/boost-serialization"
target = "//:serialization"

[[dependency]]
package = "github.com/buckaroo-pm/boost-static_assert"
target = "//:static_assert"

[[dependency]]
package = "github.com/buckaroo-pm/boost-type_traits"
target = "//:type_traits"

[[dependency]]
package = "github.com/buckaroo-pm/boost-typeof"
target = "//:typeof"

[lock."github.com/buckaroo-pm/boost-assert"]
versions = [ "1.57.0" ]
revision = "e4476f3159e98aebaa3a057bd2670653cb778d48"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.57.0" ]
revision = "ee7d5652f970bde066501c7cee1d0d2ad43c2348"

[lock."github.com/buckaroo-pm/boost-core"]
versions = [ "1.57.0" ]
revision = "9194d8422e508b914041aad8c97a55b712cf4855"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.57.0" ]
revision = "08aef274380d048f40aea0f40be03d3c943c0917"

[lock."github.com/buckaroo-pm/boost-mpl"]
versions = [ "1.57.0" ]
revision = "11c429d65c6cea226770f7abf7b4af91419af893"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.57.0" ]
revision = "701273f2c2f1da1f06a00b11ee15f30a358a775c"

[lock."github.com/buckaroo-pm/boost-serialization"]
versions = [ "1.57.0" ]
revision = "54223db315a291c1cc7c2a21e6b44acf59a7629b"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.57.0" ]
revision = "1c6733c3798004871da07f1ca08b533b1293b597"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.57.0" ]
revision = "8d3e971865e51ce40a9baa2c47c7a2f236b502ba"

[lock."github.com/buckaroo-pm/boost-typeof"]
versions = [ "1.57.0" ]
revision = "9a83b25172a84326263a7236784ed16a6df2ea6d"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.57.0" ]
revision = "672b552c874c72529564a79448c4b48b966ba7c5"
